# Generated by Django 4.0.3 on 2022-04-01 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_tag_articles_alter_tagposition_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='ArticleScope',
        ),
        migrations.RemoveField(
            model_name='tagposition',
            name='tag',
        ),
        migrations.AddField(
            model_name='tagposition',
            name='name_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.articlescope', verbose_name='Раздел'),
            preserve_default=False,
        ),
    ]
