# Generated by Django 4.0.3 on 2022-04-01 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_tag_articlescope_remove_tagposition_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='tagposition',
            name='name_tag',
        ),
        migrations.AddField(
            model_name='tagposition',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Positions', to='articles.articlescope', verbose_name='Раздел'),
            preserve_default=False,
        ),
    ]
