# Generated by Django 4.0.3 on 2022-04-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_tag_remove_articlescope_name_articlescope_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlescope',
            old_name='tag',
            new_name='scopes',
        ),
    ]
