# Generated by Django 4.0.3 on 2022-04-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_rename_tag_articlescope_scopes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlescope',
            old_name='scopes',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='article', to='articles.tag'),
        ),
    ]
