# Generated by Django 4.0.3 on 2022-04-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_tag_articles_alter_articlescope_article_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={'ordering': ['main']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
    ]
