# Generated by Django 4.0.3 on 2022-04-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_articlescope_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={'ordering': ['is_main']},
        ),
        migrations.RenameField(
            model_name='articlescope',
            old_name='main',
            new_name='is_main',
        ),
    ]
